CREATE TABLE "student_registration_achievements" (
	"id" text PRIMARY KEY NOT NULL,
	"application_id" text NOT NULL,
	"type" text NOT NULL,
	"level" text NOT NULL,
	"name" text NOT NULL,
	"year" text NOT NULL,
	"organizer" text NOT NULL,
	"school_id" text DEFAULT 'default' NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_registration_applications" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"submitted_at" timestamp NOT NULL,
	"reviewed_by_user_id" text,
	"reviewed_at" timestamp,
	"rejection_reason" text,
	"promoted_student_id" text,
	"applied_grade_level" text,
	"applied_program" text,
	"full_name" text NOT NULL,
	"gender" text NOT NULL,
	"nisn" text NOT NULL,
	"nis" text,
	"certificate_serial_number" text,
	"skhun_serial_number" text,
	"national_exam_number" text,
	"nik" text NOT NULL,
	"previous_school_npsn" text,
	"previous_school_name" text,
	"place_of_birth" text NOT NULL,
	"date_of_birth" text NOT NULL,
	"religion" text NOT NULL,
	"special_needs" text NOT NULL,
	"address_detail" text NOT NULL,
	"dusun" text,
	"rt" text NOT NULL,
	"rw" text NOT NULL,
	"kelurahan" text NOT NULL,
	"postal_code" text,
	"kecamatan" text NOT NULL,
	"kabupaten" text NOT NULL,
	"provinsi" text NOT NULL,
	"transport_mode" text NOT NULL,
	"living_arrangement" text NOT NULL,
	"home_phone" text,
	"mobile_phone" text,
	"personal_email" text,
	"kks_recipient" text,
	"kks_number" text,
	"kps_recipient" text,
	"kps_number" text,
	"pip_eligible_reason" text,
	"kip_recipient" text,
	"kip_number" text,
	"kip_holder_name" text,
	"kip_reject_reason" text,
	"birth_cert_number" text NOT NULL,
	"latitude" text,
	"longitude" text,
	"father_name" text NOT NULL,
	"father_birth_year" integer NOT NULL,
	"father_special_needs" text NOT NULL,
	"father_occupation" text NOT NULL,
	"father_education_level" text NOT NULL,
	"father_monthly_income" text NOT NULL,
	"mother_name" text NOT NULL,
	"mother_birth_year" integer NOT NULL,
	"mother_special_needs" text NOT NULL,
	"mother_occupation" text NOT NULL,
	"mother_education_level" text NOT NULL,
	"mother_monthly_income" text NOT NULL,
	"guardian_name" text,
	"guardian_birth_year" integer,
	"guardian_occupation" text,
	"guardian_education_level" text,
	"guardian_monthly_income" text,
	"height_cm" integer NOT NULL,
	"weight_kg" integer NOT NULL,
	"distance_to_school_km" integer NOT NULL,
	"travel_time_minutes" integer NOT NULL,
	"sibling_count" integer NOT NULL,
	"school_id" text DEFAULT 'default' NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_registration_nonformal_educations" (
	"id" text PRIMARY KEY NOT NULL,
	"application_id" text NOT NULL,
	"type" text NOT NULL,
	"organizer_or_source" text NOT NULL,
	"start_year" text NOT NULL,
	"end_year" text,
	"school_id" text DEFAULT 'default' NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "students" ADD COLUMN "registration_application_id" text;--> statement-breakpoint
ALTER TABLE "student_registration_achievements" ADD CONSTRAINT "student_registration_achievements_application_id_student_registration_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."student_registration_applications"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_registration_applications" ADD CONSTRAINT "student_registration_applications_reviewed_by_user_id_users_id_fk" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_registration_applications" ADD CONSTRAINT "student_registration_applications_promoted_student_id_students_id_fk" FOREIGN KEY ("promoted_student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_registration_nonformal_educations" ADD CONSTRAINT "student_registration_nonformal_educations_application_id_student_registration_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."student_registration_applications"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_registration_application_id_student_registration_applications_id_fk" FOREIGN KEY ("registration_application_id") REFERENCES "public"."student_registration_applications"("id") ON DELETE no action ON UPDATE no action;