ALTER TABLE "teachers" ADD COLUMN "date_of_birth" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "place_of_birth" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "mother_name" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "address_detail" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "dusun" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "rt" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "rw" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "kelurahan" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "postal_code" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "kecamatan" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "kabupaten" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "provinsi" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "nik" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "npwp" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "taxpayer_name" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "marital_status" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "spouse_name" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "spouse_occupation" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "employment_status" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "niy_nigk" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "nigb" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "nip" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "nuptk" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "ptk_type" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "appointment_decree_number" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "appointment_effective_date" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "appointment_decree_issuer" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "cpns_decree_number" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "cpns_effective_date" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "pns_effective_date" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "rank_grade" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "salary_source" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "assignment_letter_number" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "assignment_letter_date" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "assignment_effective_date" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "is_home_school" boolean;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "is_principal_licensed" boolean;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "vocational_program_code" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "special_needs_types_handled" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "special_needs_specialization" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD COLUMN "special_needs_skills" text;--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_nik_unique" UNIQUE("nik");--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_niy_nigk_unique" UNIQUE("niy_nigk");--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_nigb_unique" UNIQUE("nigb");--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_nip_unique" UNIQUE("nip");--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_nuptk_unique" UNIQUE("nuptk");